version: '3'

services:
  pgdb:
    image: postgres:15
    environment:
      POSTGRES_DB: "payment_db"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "payment_password"
    ports:
      - "5432:5432"
    container_name: pgdb

  payment_bot:
    build: .
    command: python payment_bot/polling_mode.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb