version: '3'

services:
  pgdb:
    image: postgres:15
    environment:
      POSTGRES_DB: "payment_db"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "payment_password"
    ports:
      - "5432:5432"
    container_name: pgdb

# Для хуков нужно поднимать ngrok, доставать из него url, биндить его в settings и в настройках CloudPayments,
# Либо реализовывать через белый айпишник

  payment_bot:
    build: .
    command: ["uvicorn", "payment_bot.webhooks_mode:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - pgdb