version: '3'

services:
  payment_bot:
    build: .
    command: python /usr/src/app/payment_bot/polling_mode.py
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "payment_db"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "payment_password"
    ports:
      - "5432:5432"
    container_name: pgdb